name: en-list

on:
  schedule:
    - cron: "0 3 */2 * *" # 毎日03時に実行
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Create directory
        run: |
          current_month=$(date +'%Y%m')
          current_week=$(date +'%Y_%W') # 1-51
          day_offset=$(( 7 - current_day_of_week ))
          current_time=$(date +'%Y%m%d_%H%M')
          folder_name="dj_rss_EN_${current_week}"
          mkdir -p $folder_name
      
      - name: Install required libraries
        run: pip install notebook requests bs4 dropbox pandas
      - name: Run scraper
        run: python wsj_en.py

      - name: Set Git Config
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
        working-directory: ${{ github.workspace }}

      # リモートリポジトリの変更を取り込む
      - name: Pull remote changes
        run: git pull origin main
        working-directory: ${{ github.workspace }}
      
      # XMLファイルを指定のフォルダに格納
      - name: Move XML files to folder
        run: |
          mv *.xml $folder_name/
        working-directory: ${{ github.workspace }}

